name: movie_app
description: "A feature-rich movie application built with Flutter that enables users to discover, search, and explore a wide range of movies. The app integrates with an external API to fetch real-time movie data, including ratings, genres, and detailed descriptions. It follows clean architecture principles and provides a responsive and smooth user experience."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: any
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.0.9
  vector_graphics: ^1.1.11
  flutter_bounceable: ^1.2.0
  animated_toggle_switch: ^0.8.7
  flutter_easyloading: ^3.0.5
  toastification: ^3.0.3
  google_fonts: ^8.0.0
  http: ^1.6.0
  cached_network_image: ^3.4.1
  provider: ^6.1.5+1
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  highlight_text:
  toggle_switch: ^2.3.0
  flutter_launcher_icons: ^0.14.4
  device_preview: ^1.3.1
  shared_preferences: ^2.5.4
  cloud_firestore: ^6.1.3
  flutter_bloc: ^9.1.1
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  google_sign_in: ^7.2.0
  firebase_storage: ^13.1.0
  carousel_slider: ^5.0.0
  youtube_player_flutter: ^9.0.1
  flutter_inappwebview: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  flutter_gen_runner:
flutter_gen:
  output: lib/core/gen/
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true
flutter_launcher_icons:
  android: "movie"
  ios: true
  image_path: "assets/images/launcher_ico.png"
  min_sdk_android: 21




flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
