// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1GTWakcoWeF5YmCop7H4ofKovfCaqpA',
    appId: '1:346692131751:android:b613a0efee8fe01c263482',
    messagingSenderId: '346692131751',
    projectId: 'abdullah-movie-app',
    storageBucket: 'abdullah-movie-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRylyiV3AVgu-no2Rh0eSDn7Je2hxdVpg',
    appId: '1:346692131751:ios:cf22175cde525f49263482',
    messagingSenderId: '346692131751',
    projectId: 'abdullah-movie-app',
    storageBucket: 'abdullah-movie-app.firebasestorage.app',
    androidClientId:
        '346692131751-87mkfe20jc8bcqe1b5n8m1nnis25g9e9.apps.googleusercontent.com',
    iosClientId:
        '346692131751-522ql1t5t1qp2jbs7e0kd6n83vha299i.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
